print("How old are your", end =' ')
age = input()
print("How tall are you?",end = ' ')
height = input()
print("How much do you weight?", end = ' ')
weight = input()
print("What's your sex?", end = '')
sex = input()
print(f"So, you're a {age} old, {height} tall and {weight} heavy {sex}")
